### ISSUE TITLE
Add additional Mocha test scripts

### ISSUE THREAD

**Issue by ignoreintuition** [ignoreintuition/jSchema#5]
Currently Mocha test script have about 15% coverage.  Need to add additional test scripts to test all functions, additional functionality of methods already covered.

**Comment by codeofdiego** [comment]
Hi, i'm a Technology of Information student and i'm currently taking Software Test classes with a fried. As our course project is it possible to maximize the coverage of your framework's tests and create a report for our professor? We have 2 weeks to present it.

**Comment by ignoreintuition** [comment]
I would love that. I am using Mocha. Let me know if you need any requirements and I’ll be happy to peer review anything you write. 

Appreciate the assistance.

**Comment by codeofdiego** [comment]
Great, your code is very straight forward and the comments are helping. I'll keep you updated of my progress.

**Comment by ignoreintuition** [comment]
Excellent.  I'll keep an eye out for PRs.

**Comment by codeofdiego** [comment]
@ignoreintuition How are you calculating coverage? Using Instanbul?

**Comment by ignoreintuition** [comment]
Instanbul will work.  I added it in as a dependency in the NPM package.json and updated the test script.

**Comment by codeofdiego** [comment]
Created the PR for the new tests. Found 2 issues when executing the new script and fixed them, but please double check the changes to the jschema file to make sure i got it right. Hope everything goes well.

**Comment by ignoreintuition** [comment]
Looks good.  I tested it against the lastest release 0.5.4 and it worked perfectly.   Thank you again.
